version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - TESTNET=${TESTNET}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET=${BINANCE_SECRET}
      - MT5_LOGIN=${MT5_LOGIN}
      - MT5_PASSWORD=${MT5_PASSWORD}
      - MT5_SERVER=${MT5_SERVER}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DISABLE_AUTH=${DISABLE_AUTH}
      - AI_SERVICE_URL=http://ai-service:5000
    volumes:
      - ./backend/src:/app
      - ./config:/app/config
    depends_on:
      - redis
      - postgres
      - ai-service
    networks:
      - trading-network

  ai-service:
    build: ./ai-service
    ports:
      - "5000:5000"
    environment:
      - DEBUG=${DEBUG}
      - MODEL_TYPE=${MODEL_TYPE:-mock